# Generated by Django 4.1.2 on 2022-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='xpos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='ypos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
